### ISSUE TITLE
Support new Geo types import from WKT

### ISSUE THREAD

**Issue by mflaxman10** [omnisci/pymapd#115]
Now that geo types have landed, it would be great to see a pymapd update accommodate them directly.  Currently we are limited to importing geometries as independent columns, or as strings.  The only way to get true points, for example, is to re-export as CSV and then re-import.  This is awkward and inefficient.

Current Behavior:
WKT columns treated as strings
latitude, longitude columns treated as independent numeric columns.

Expected Behavior:
Generally, as in Immerse "Import" and "Copy From" behave.
For adjacent x,y columns, with a table DDL defining Point, have table uploads create Points.
For supported WKT types, have column type set by WKT geometry type (POINT() -> POINT, etc.)

**Comment by randyzwitch** [comment]
While I agree with the sentiment, I'll have to look into whether our Thrift bindings actually support this. I think it's the case that the geo portion that allows you to load from mapdql is separate from the regular Thrift `load_table` methods.

So we might not be able to pass the data in without doing some sort subprocess drop into a mapdql shell, which could be tough.

**Comment by mflaxman10** [comment]
Multiple implementations could support the same functionality from the user perspective.  In terms of architecture and documentation, it would be optimal if the same core code could handle geo transformations, regardless of source.  At the moment, there are slightly-different capabilities depending on the import path (mapdql, thrift, copy from).  Coding geo-Thrift could perhaps be a big task since the given primitives are perhaps not well suited (you might have to re-implement http://www.opengeospatial.org/standards/sfa).  So perhaps cleaner and simpler to implement a post-thrift load_table hook.  This code already exists, since it is used in immerse and 'copy from.'  For example, given separate but adjacent latitude, longitude float columns, it constructs points; given supported WKT, it constructs appropriate geometries.  Perhaps this request could be reformulated as: 'after thrift import, can we apply the same geo-column detection and processing as for import geo'.

**Comment by mflaxman10** [comment]
Confirmed Randy's load_table_rowwise works as expected.  My notes:
<li>First, the <code>load_table()</code> method given a dataframe won't work as expected by most users. It will create a table with a text column instead of geometry
<li><code>load_table_rowwise()</code> is currently the only in-memory method which interprets wkt geometry.  However this method requires explicit creation of the table DDL beforehand, and passing the data as Python tuples as not a Pandas dataframe.
<li>Specifically, the rowwise() method requires an iterator returning raw tuples.  Pandas provides a dataframe.itertuples() iterator, which is indeed what we need.  But by default, Pandas returns tuples named "Pandas()" with an index value, neither of which OmniSci will accept.  <li>Passing itertuples() the parameters <code>index=False</code> and <code>name=None</code> gets us raw tuples which work fine!

I'd propose we close this issue and move it to a doc update request for pymapd load_table section.  Probably cleanest in one section called something like "loading geodata"

**Comment by mflaxman10** [comment]
In support of the geopandas option, here are the steps I currently take (and still need to blog document) for taking a normal pandas dataframe and converting to OmniSci-compatible dataframe:

import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

1) Create a new coordinates column with tuples of column coordinates (not necessarily WGS84 lat lon):    
<code>df['Coordinates'] = list(zip(df.lon, df.lat))</code>

2) Create binary Shapely points from coordinate tuples (because required for geopandas):
<code>df['Coordinates'] = df['Coordinates'].apply(Point)</code>

3) Create a new geopandas dataframe (needed temporally in most cases to force projections to 4326):
<code>gdf = geopandas.GeoDataFrame(df, geometry='Coordinates')</code>

4) Establish input coordinate system from metadata, and set it:
<code>gdf.crs({init: 'EPSG:XXXX'})

5) Now that set, reproject to  WGS84 lat/lon:
<code>gdf4326 = gdf.to_crs({init: 'EPSG:4326'})</code>

6) Now that geopandas coordinate column is in correct projection/datum, force back to WKT from binary:
<code>def row2wkt_point(p):
    return(p.to_wkt())
df['location'] = df['Coordinates'].apply(row2wkt_point)</code>

7) Drop extra and or confusing columns:
<code>df.drop({'Coordinates','lat','lon'}, axis=1, inplace=True)</code>

8) Create a custom DDL for this file:
<code>    conn.execute('CREATE TABLE clim_streamflow (stream_flow float, location GEOMETRY(POINT, 4326), yearint int)') </code>

9) Finally.... load table rowwise into OmniSci, being sure to avoid the 4 got'chas above (rowwise, without index, unnamed tuples iterator):
<code>    conn.load_table_rowwise("clim_streamflow2060", streamflow2060df.itertuples(index=False, name=None))</code>

So... one of the most commonly-desired open source geodata import pathways requires 9 steps, with 'inside baseball' knowledge that most geospatial or database experts would not have.  I guess I should also note that several of these steps are also computationally time-consuming.  The speed issue is bad enough to be noticeable in raw Python 3.6 even for image tiles of 1k x 1k - and really terrible for LIDAR type applications.  

A geopandas import implementation would avoid all the back-and-forth from text to binary and back, and the metadata loss/re-establishment.

**Comment by randyzwitch** [comment]
Just added a bunch of tests for geospatial row-wise, it's not that complex though it does require creating the table definition upfront:

https://github.com/omnisci/pymapd/blob/master/tests/test_data_no_nulls_cpu.py#L182-L273

I'm hoping to work on the documentation in the next few weeks, making sections for working with various types of data. With a fully worked example in the documentation, hopefully the guessing about what works will start to be minimized.

**Comment by randyzwitch** [comment]
I'm closing this in lieu of #109, an update to the documentation.
