### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#131]
pandas will drop Python 2 support January 1st 2019, and pyarrow I believe dropped python 2 support for 0.11. The writing is on the wall, so in the new year, we should clean up the codebase (i.e. remove all the six shims) and stop supporting Python 2 as well.

Users wanting to use Python 2 will still be able to do so with previous versions of pymapd (as of now, pymapd still supports Python 2)

**Comment by randyzwitch** [comment]
Could time this with OmniSci 5.0 release, whenever that will be, so that it's an obvious break.

**Comment by xhochy** [comment]
FYI: Arrow still supports Python 2, we have no exact plans but also won't keep it for long anymore.

**Comment by hugovk** [comment]
Please PR #155.
