### ISSUE TITLE
Password File similar to pgpass

### ISSUE THREAD

**Issue by zacharymostowsky** [omnisci/pymapd#136]
Hi OmniSci Community,

I am using the pymapd connector to successfully connect my python program to my MapD database. Currently, the user credentials are stored in my code as plain text. I was wondering if there was a tool that existed similar to a pgpass file for postgres. I would like to store my password in some sort of separate document from the code. Is this possible?

If it matters… Using Python 3.6.6 on a Windows 10 Enterprise machine. Making connection to mapd running on Rhel 7 Server.

Thanks,
Zach

**Comment by randyzwitch** [comment]
Closing in lieu of discussion on the community forum:

https://community.omnisci.com/t/pymapd-password-file/1830/2
