### ISSUE TITLE
Add support for DICT encoding

### ISSUE THREAD

**Issue by mattdlh** [omnisci/pymapd#140]
Add support for DICT encoding in mapd db. Should be applies to fields where appropriate for the DataFrame

**Comment by randyzwitch** [comment]
Related #114 

In general, I shouldn't be that hard to add support for dict encoded strings, it's more of thinking through the logic we want to use (or, just always using dict encoding, which doesn't require any logic at all)

**Comment by tmostak** [comment]
Given we can’t do much (group by or join on) none encoded strings, I think we should start with defaulting to text encoded strings. Later we can figure out something smarter if we want. 

Can this be prioritized? (It’s currently a fairly bad experience)

**Comment by randyzwitch** [comment]
Yes, I can work on this tomorrow
