### ISSUE TITLE
TMapDException: Column date_ requires arrow support for i32 dates

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#141]
@jp-harvey I think this is related to your PR #138, though not sure why it didn't get caught before.

I merged in Andrew's cudf PR #139 and now the tests complain about dates as int:
https://travis-ci.org/omnisci/pymapd/jobs/474545829

**Comment by andrewseidl** [comment]
This is probably a casualty of some of the date and timestamp compression changes in v4.4.1. A fix for this one is already in the works, will be in the next release.

**Comment by randyzwitch** [comment]
Thanks for catching that @andrewseidl, I'm fine with the Docker solution if you are

**Comment by andrewseidl** [comment]
New Docker image tagged as latest, built from mapd-core master as of this morning.

Could you try triggering a rebuild of #142?

**Comment by randyzwitch** [comment]
@andrewseidl It still fails

**Comment by randyzwitch** [comment]
Closed, fix by Docker update unrelated to pymapd specifically
