### ISSUE TITLE
ModuleNotFoundError: No module named 'pymapd.shm'

### ISSUE THREAD

**Issue by prajwal-wale** [omnisci/pymapd#145]
It's connecting to DB but If I try to query using select_ipc (cpu), I'm getting "pymapd.shm" Module not found error.
@randyzwitch  please see the screenshot for more details and any advice and suggestions will be greatly appreciated.
![screenshot 2019-01-07 at 12 11 34 pm](https://user-images.githubusercontent.com/32243091/50752779-66ff6d00-1275-11e9-81ce-41371be94a07.png)
![screenshot 2019-01-07 at 12 12 22 pm 2](https://user-images.githubusercontent.com/32243091/50752845-9e6e1980-1275-11e9-9979-8677e6afdcab.png)

`from pymapd import connect
con = connect(user="mapd", password= "HyperInteractive", host="localhost", dbname="mapd")
print(con)
query = "SELECT depdelay, arrdelay FROM flights_2008_10k limit 100"
df = con.select_ipc(query)
df.head()`

**Comment by randyzwitch** [comment]
Hi @prajwal-wale - 

What version of pymapd are you using and how did you install it? I'm not too familiar with pycharm, but I did test this exact query against pymapd master using conda on Ubuntu 18.04LTS and it `select_ipc` worked, so this points to an installation error of some sort.

**Comment by prajwal-wale** [comment]
@randyzwitch Thank you for you're valuable feedback.
I used pymapd version 0.5.1 and it is installed using Conda env (conda install -c conda-forge pymapd) command in Mac OS Mojave. I'll try it in Ubuntu and I'll let you know if any problem occurs.

**Comment by randyzwitch** [comment]
Thanks @prajwal-wale. I can confirm this error using pip via a Docker container, but with conda it should work. Note that the latest version of pymapd is 0.6.0, so you might try that first via conda.

**Comment by prajwal-wale** [comment]
@randyzwitch I'm using docker container. But with "conda install -c conda-forge pymapd==0.6.0". It's not installing. If I try giving pymapd w/o version, version 0.5.1 getting installed. My pyarrow version is 0.11.1.
Please give me advice on this...

**Comment by prajwal-wale** [comment]
Thank you @randyzwitch . Now I can connect to localhost and query using pymapd. But I'm not able to connect to other DB's. kindly give advise to connect to other DB's using pymapd.connect
(The error i'm getting is in below screenshot)
![image](https://user-images.githubusercontent.com/32243091/50967012-d76bef80-14fc-11e9-9746-c4c7f9c2c73a.png)

**Comment by randyzwitch** [comment]
Without knowing the actual values for your install (please don't post them! :) ), it's hard to tell what the issue might be. However, this just worked on my computer:

```python
In [11]: uri = "mapd://mapd:HyperInteractive@localhost:9092/mapd?protocol=http"                                    

In [12]: con = pymapd.connect(uri)                                                                                 

In [13]: print(con)                                                                                                
Connection(mapd://mapd:***@http://localhost:9092/mapd?protocol=http)
```

So based on how you are running OmniSci, you'll need to figure out the proper port to connect to. `9092`, and `443` are common, but again, it's up to your install.
