### ISSUE TITLE
Remove benchmarks directory?

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#159]
Given that pymapd primarily relies on pyarrow, pandas and OmniSci in general, not sure what value the benchmarks directory here provides:

https://github.com/omnisci/pymapd/tree/master/benchmarks

I'm open to keeping it if @jp-harvey @andrewseidl or others think it has value.

**Comment by randyzwitch** [comment]
Note: I _think_ the benchmarks directory is separate from the `bench.py` script here (which appears much more robust)

https://github.com/omnisci/pymapd/blob/master/scripts/bench.py

**Comment by andrewseidl** [comment]
Seems fine to remove, they're easy enough to recreate once someone decides to maintain+improve them.
