### ISSUE TITLE
Default install with conda causing older pymapd version getting installed

### ISSUE THREAD

**Issue by tshah-ivp** [omnisci/pymapd#162]
Running the conda install command  [_conda install -c conda-forge -c nvidia -c rapidsai -c numba -c defaults pymapd cudf python=3.6_   ] causes an older version of pymapd (0.3.2) getting installed . Can this be caused due to new cudf  [0.5.0] release pinned to pyarrow[0.12.0] ?

_conda list output_ 
....
pymapd   |                 0.3.2     |               py36_0   |  conda-forge
cudf         |            0.5.0          |         py36_18     | rapidsai
libcudf     |             0.5.0         |      cuda9.2_18    |  rapidsai
libcudf_cffi |              0.5.0      |      cuda9.2_py36_18 |     rapidsai
pyarrow     |             0.12.0     |      py36hbbcf98d_2  |   conda-forge
....

**Comment by randyzwitch** [comment]
For now, you'll need to pin cudf to 0.4 and it should give you pymapd 0.7.1

`conda install -c conda-forge -c nvidia -c rapidsai -c numba -c defaults pymapd cudf=0.4 python=3.6`

Our next release supports Arrow 0.12, which will then make cudf 0.5 install as well. If you're adventurous, pymapd master already has Arrow 0.12 support, so you could also install that way to use cudf 0.5.

**Comment by tshah-ivp** [comment]
Thanks will try to use master and also It seems cudf doesnot have 0.4 on main label but on cf201901

**Comment by randyzwitch** [comment]
I know that with conda-forge switching compilers, cudf has been having some problems. I just installed using `conda install -c conda-forge -c nvidia -c rapidsai -c numba -c defaults pymapd cudf=0.4 python=3.6` yesterday, and today it doesn't work.

Not sure what to tell you, maybe install cudf via conda to get 0.5 and install pymapd via pip in the same conda environment. For better or worse, pip doesn't check dependencies, so pymapd 0.7.1 should install fine (we don't have any specific pyarrow code for 0.12, so you don't *need* master)

**Comment by randyzwitch** [comment]
This does it (as of this exact instant):

`conda install -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c rapidsai/label/cf201901 -c numba -c conda-forge -c defaults cudf pymapd=0.7.1`

We'll keep an eye on this, unfortunately it seems like conda-forge is a bit of a free-for-all
