### ISSUE TITLE
Dates handled improperly on load

### ISSUE THREAD

**Issue by stets** [omnisci/pymapd#167]
After speaking with @randyzwitch  we found that `DATE` types are handled in mapd 4.4 as epoch days rather than epoch seconds. After loading data via pymapd, dates can be found to be invalid:

![image](https://user-images.githubusercontent.com/2044547/52507257-f8d4ff80-2bbe-11e9-9d5b-e77339b5b613.png)

Expected Behavior:
- Dates show up when selected

Observed Behavior:
- Dates do not show up -- invalid date shows up

Reproduction:

Create table in OmniSci:
```
CREATE TABLE sales (
saleDate DATE
)
```

load dates
```
import pandas as pd
import pymapd

mapdcon = pymapd.connect(user=mapduser, password=mapdpass, host=mapdhost, dbname=mapddbname, port=mapdport, protocol=mapdprotocol)

# Create some dates
dates = pd.date_range('20190101', periods=10)
df = pd.DataFrame(dates)

# load into mapd 
mapdcon.load_table_columnar('sales', df, preserve_index=False)
```

**Comment by randyzwitch** [comment]
Per internal discussion;

> Yes, this will require an update in the connector. You will need to read the encoding on the SQLType of the column you are inserting data into. If the encoding is FIXED or NONE, you need to use seconds. If the encoding is DATE_IN_DAYS, you need to use days.
