### ISSUE TITLE
Add support for cudf 0.6.0

### ISSUE THREAD

**Issue by andrewseidl** [omnisci/pymapd#184]
Should be getting released any day now. One of the main new features for us is string support.

**Comment by randyzwitch** [comment]
Positive news here is that pymapd 0.9 and cudf 0.6 install together cleanly in a fresh conda environment. Still need to evaluate actually running code.

**Comment by randyzwitch** [comment]
Closing this in lieu of #191. Technically, cudf 0.6 works with pymapd as an optional import, the question is really around providing it works for all the data types. Have separate issues outstanding for those.
