### ISSUE TITLE
Arrow load leads to incorrect results in omnisci core

### ISSUE THREAD

**Issue by wamsiv** [omnisci/pymapd#190]
Steps to reproduce:

```
import pyarrow as pa
import pandas as pd

conn.execute("CREATE TABLE wam_dates_arrow(a date)")

s = pd.Series([date(2018, 12, 31), None, date(2000, 1, 1)])
arr = pa.array(s)

conn.load_table('wam_dates_arrow', pd.DataFrame(arr.to_pandas()))
conn.select_ipc("select a from wam_dates_arrow")
```

This is a small issue with core side, I am opening a PR there to fix this, opening an issue here to document this.

**Comment by wamsiv** [comment]
Update: PR https://github.com/omnisci/mapd-core-internal/pull/3220 has been merged, test and validated. Arrow imports should be good now.

**Comment by randyzwitch** [comment]
Did this make it to 4.6 @wamsiv? If so, should probably close

**Comment by wamsiv** [comment]
Yes, it did, forgot to close this. Thank you.
