### ISSUE TITLE
Evaluate removing Thrift columnar as an option

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#192]
As part of #191, it feels like if we can prove that 'columnar' and Arrow provide the same functionality for the same data types, we should remove Thrift columnar. This would remove a code path for maintenance, as well as remove a potential source of confusion (since Arrow technically is columnar, and in the case of `load_table` with the `infer` option, a user might already be using Arrow and not know it)

It's likely the case that row-wise loading will need to stay for the near-term, as it is the only way currently to load geospatial data.

**Comment by jp-harvey** [comment]
Noting that the columnar load contains some options that the others do not - match by column name and chunking data loads come to mind. These features could presumably be added for the Arrow load as well.

**Comment by randyzwitch** [comment]
Closing this for now, per https://github.com/omnisci/pymapd/issues/213 and https://github.com/omnisci/pymapd/issues/204 . Currently, the Arrow loader passes through whatever we give it, but our backend is still looking for specific input data types. And the native Arrow Table and RecordBatch loaders also don't quite work as expected
