### ISSUE TITLE
Update Thrift bindings for 4.6

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#226]
The Thrift bindings were re-factored in 4.6, regenerate the Python bindings just to ensure everything in sync.

**Comment by randyzwitch** [comment]
Note that for this, need to ensure that unnecessary imports removed, to avoid reintroducing issue arising in past where unneeded imports caused issues when trying to use reticulate from R

**Comment by andrewseidl** [comment]
Also beware that a few things were split out and rearranged a couple days ago in master, so you might need to handle a new `common` module.

**Comment by randyzwitch** [comment]
Closed by #228
