### ISSUE TITLE
Copy From parquet not supported?

### ISSUE THREAD

**Issue by mflaxman10** [omnisci/pymapd#235]
Tried with some real data with lat/lon, intending to test import performance (since parquet writes are many x faster than csv, hoping reads would be as well).

Confirmed same issue with simple two column fake data...import fails with binary displayed to error log:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/2546667/57564086-421e2200-735b-11e9-82d8-8780d3fc00f0.png">

df.to_parquet('rcp98_2026_2045_windspeed.parquet')
fullpath = '/mapd4TB_2/demo/climate/rcp98_2026_2045_windspeed.parquet'
mapdql(f"COPY {table_name} FROM '{fullpath}' WITH (lonlat='false');")

E0511 02:33:11.758389 12109 Importer.cpp:1810] Incorrect Row (expected 4 columns, has 1): [@?}ϣ=?]
E0511 02:33:11.754604 12122 Importer.cpp:306] Unmatched quote.
E0511 02:33:11.751510 12113 Importer.cpp:1810] Incorrect Row (expected 4 columns, has 3): [Xm??}?բO?@g????@?$ϥ@?ΝF#@??]L3}@?csz?T@z?@????@??Ed????YNB?
                   ?????Jf????t??C?????oD??@?݂[-@??c?`@?3?????M??G, ????Y??@?o[?+@xP{Q@Q<~?@T|????@?`Numt??????9???4?j?ka@?
                                                                                                                          C???@)?ǺX@	?̺5?@?????@1)>>!{@|X?a%?@o>?9m?@{ h???@?B?=???@?\?/S@???t???;??F?@a??~??@?pF??^@i???8@??y?y?@?\F?i}@?, AF@?@??)b?e@0??O@w	?

**Comment by dwayneberry** [comment]
@mflaxman10 you need to add `with (parquet='true') ` on your copy command 

See the docs at https://www.omnisci.com/docs/latest/6_loading_data.html#parquet

**Comment by mflaxman10** [comment]
Thanks @dwayneberry   I evidently forgot to RTFM - its even the (newly) documented behavior
