### ISSUE TITLE
Upgrade pyarrow

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#245]
Evaluate whether we can loosen the upper bound of the pyarrow dependency

**Comment by randyzwitch** [comment]
We do not currently support pyarrow 0.14, as some breaking changes were made between 0.13 and 0.14. Specifically, the following passage _could_ be our issue, which is resolved directly in OmniSciDB:

```
The dictionary API has been reworked in ARROW-3144. The dictionary values used to be tied to the DictionaryType instance, which ended up too inflexible. Since dictionary-encoding is more often an optimization than a semantic property of the data, we decided to move the dictionary values to the ArrayData structure, making it natural for dictionary-encoded arrays to share the same DataType instance, regardless of the encoding details.
```

**Comment by xhochy** [comment]
There is also the 0.15.x series out now.

**Comment by randyzwitch** [comment]
Thanks @xhochy, we’re evaluating if we can jump right to 0.15

**Comment by mikehinchey** [comment]
Pymapd now uses `pyarrow 0.15.0`
