### ISSUE TITLE
Support all slash commands in pymapd

### ISSUE THREAD

**Issue by realtonyyoung** [omnisci/pymapd#274]
Customer is requesting that we provide equivalent methods to all omnisql `\` commands in pymapd. Also would like them documented with their omnisql equivalencies

**Comment by realtonyyoung** [comment]
@wamsiv

**Comment by randyzwitch** [comment]
This isn't necessarily feasible and/or desirable. The backslash commands in omnisql have custom code that is part of the codebase, not necessarily Thrift endpoints which is what pymapd wraps. It would make sense for that code to move to backend Thrift endpoints for re-use, but shelling into omnisql remotely isn't a great idea

**Comment by esamuel1** [comment]
Tagging this issue as well as other customers have asked for this. The first pass of this implementation should support \d. This is currently blocked by: https://github.com/omnisci/omniscidb/issues/215

**Comment by mikehinchey** [comment]
OmniSci DB now supports SQL commants: `show tables` and `show create table`. Further requests should be made to https://github.com/omnisci/omniscidb to support more `SHOW` commands.
