### ISSUE TITLE
Update array import tests to use distinct values

### ISSUE THREAD

**Issue by andrewseidl** [omnisci/pymapd#322]
As mentioned in https://github.com/omnisci/pymapd/pull/321/files/9fc6074a7739ccb4636ad092ccdc973bf6538c1b#r437847652 the array import tests currently use a couple values of `[1, 2]` in the test data. It turns out this ends up hiding a bug in omniscidb where incorrect values end up getting inserted for bigint arrays. Update this test to use distinct values once the bugfix in omniscidb makes its way out.

**Comment by xmnlab** [comment]
@andrewseidl is there already any issue or PR addressing this bug on omniscidb side?

**Comment by andrewseidl** [comment]
Sorry, yes, it was resolved with https://github.com/omnisci/omniscidb/commit/d368d7fb306fabd39cbe8d107b5dc08006bc83ec

**Comment by xmnlab** [comment]
thanks for the updates! I will work on the new tests.
