### ISSUE TITLE
load_table_columnar with high precision timestamp produces incorrect values

### ISSUE THREAD

**Issue by kchu-mapd** [omnisci/pymapd#326]
Issue reproducible with pymapd version 0.23.0

Steps to reproduce:
1. Create a test table:
```
CREATE TABLE t3(col_ts TIMESTAMP(6));
```
2. Run the following sample code with Python:
NOTE: You may want to change the database connection string for your test environment.
```
import pymapd
import pandas as pd

test_list = []
test_list.append({'col_ts': '2020-05-07T12:55:33.708089'})
test_list.append({'col_ts': '2020-05-07 12:55:33.708089'})
df = pd.DataFrame(test_list)
conn = pymapd.connect(user='mapd', password='HyperInteractive', host='minos.mapd.com', port=6274, dbname='mapd', protocol='binary')
conn.load_table_columnar(table_name='t3', data=df, preserve_index=False)
```
3. Now run a simple SQL from the backend.
```
omnisql> select * from t3;
col_ts
1970-01-01 00:26:28.856133
1970-01-01 00:26:28.856133
```

**Comment by xmnlab** [comment]
@kchu-mapd do you know if the error persist with pymapd 0.24?

**Comment by mflaxman10** [comment]
Seems to be working fine in 0.24:
![image](https://user-images.githubusercontent.com/2546667/92768746-2b238180-f34d-11ea-8a66-f1f4570580cf.png)
