### ISSUE TITLE
TypeError: thrift_cast() got an unexpected keyword argument 'is_array'

### ISSUE THREAD

**Issue by bry100lee** [omnisci/pymapd#332]
When using load_table_columnar('<table_name>',df,preserve_index=False,col_names_from_schema=True) and if the table has a decimal column, the following error is thrown:

`TypeError: thrift_cast() got an unexpected keyword argument 'is_array'`

The error seems to indicate the thrift_cast function is being called with 4 parameters, while it only accepts 3.

**Comment by xmnlab** [comment]
thanks @bry100lee for the information. I will take a look into that.

**Comment by realtonyyoung** [comment]
@xmnlab any update on this issue?

**Comment by xmnlab** [comment]
@realtonyyoung IIRC it is missing just the tests. I will try to go back to that PR today. thanks!
