### ISSUE TITLE
Loosen dependencies for pandas/pyarrow

### ISSUE THREAD

**Issue by TristenHarr** [omnisci/pymapd#363]
The v0.25.1 setup.py file appears loosens support for pandas, however v0.25.1 is not available via PyPi.

pyarrow released v3.0.0 in January, can support be added for this as well?

**Comment by mikehinchey** [comment]
pymapd is replaced by https://github.com/omnisci/pyomnisci. Please file issues there or at https://community.omnisci.com/.

pyomnisci uses pyarrow 3.0.0 now and will soon upgrade to 5.0.0.
