### ISSUE TITLE
select_ipc_gpu dataframe does not get cleared from GPU memory

### ISSUE THREAD

**Issue by anirudh-here-com** [omnisci/pymapd#365]
We are using pymapd to get data in gpu dataframe using select_ipc_gpu. We observed that over time, the memory usage of omnisci in GPU keeps increasing until entire memory gets filled.
Is there a way to clear it periodically?

Regards,
Anirudh Simha

**Comment by mikehinchey** [comment]
Hi Anirudh,

Thank you for the report. This does appear to be a problem in the OmniSci DB, not the python client, but I don't have a timeframe to fix it yet.  I believe you have an issue open on the DB, so I'll close this issue.

I did create a related issue for the pyomnisci library (which is the replacement for pymapd) in https://github.com/omnisci/pyomnisci/issues/17

Thanks,
Mike
