### ISSUE TITLE
select_ipc error

### ISSUE THREAD

**Issue by baldeaglelabs** [omnisci/pymapd#77]
Couple of questions:
Does pymapd require python3x
I am using python 2.7 on a mac pro 
community edition MapD

Trying a simple query "SELECT depdelay, arrdelay FROM flights_2008_10k LIMIT 100"
Getting an error while trying to query
Works with con.execute(query)
but fails when trying
df = con.select_ipc(query)

  File "/Users/username/anaconda2/lib/python2.7/site-packages/pymapd/connection.py", line 308, in select_ipc
    sm_buf = load_buffer(tdf.sm_handle, tdf.sm_size)
  File "pymapd/shm.pyx", line 31, in pymapd.shm.load_buffer
  File "pymapd/shm.pyx", line 36, in pymapd.shm.load_buffer
ValueError: Invalid shared memory key 719885386

Any help is appreciated.
Thanks

**Comment by baldeaglelabs** [comment]
tried importing geojson.
It reported a success
But I did not see anything in data manager showing that file.

**Comment by andrewseidl** [comment]
Hi, Python 2.7 is the minimum supported so you should be good there.

Are you running MapD locally or on a remote server? `select_ipc` uses shared memory/IPC, which limits you to running the client on the same machine as `mapd_server`. We could probably improve the error message and documentation to clarify this.

Immerse and general questions about using MapD are best directed at our [Community Forums](https://community.mapd.com/). Try reloading Immerse to see if that brings up the new table. If not, check the server logs to see if there are any hints in there (default log location is `/var/lib/mapd/data/mapd_logs`. If you're still having issues, could you create a post over on the Forums and, if possible, provide the geojson file that you're trying to import?

**Comment by baldeaglelabs** [comment]
Thanks for your message. Running MapD locally in a docker container, and trying to access it from mac terminal. So, looks like it is not expected to work because MapD in not remote here. Is that correct?

**Comment by randyzwitch** [comment]
@baldeaglelabs I'm closing this issue as it appears that the Docker IPC flag is the answer, but if you are still having issues with this, please let us know and we can re-open this.
