### ISSUE TITLE
arrow: add support for Arrow 0.10.0

### ISSUE THREAD

**Issue by andrewseidl** [omnisci/pymapd#84]
The unit tests include some pre-generated copies of Arrow batch data+schema buffers, which are version specific.

These need to either be updated to be generated with Arrow 0.10.0, or else we should look into generating on the fly, as @pearu did in https://github.com/gpuopenanalytics/pygdf/pull/200

There are also some minor changes required `py_buffer` vs `frombuffer`.

Note: the current builds of mapd-core in https://hub.docker.com/r/mapd/core-os-cpu/ are still built with Arrow 0.7.1. I'll have to push a build with 0.10.0 for the Travis tests to use. For local testing, mapd-core can be built with either 0.7.1 or 0.10.0.

**Comment by pearu** [comment]
Arrow 0.7.1 does not define py_buffer. It was introduced in 0.9.0, see
https://issues.apache.org/jira/browse/ARROW-2292 .

The renaming `frombuffer` to `py_buffer` can be done after dropping arrow 0.7.1 support.

For updating the unit tests, please review
  https://github.com/mapd/pymapd/pull/85

**Comment by randyzwitch** [comment]
Was this closed by #94 or is there still work to do?

**Comment by andrewseidl** [comment]
Sorry, yes, this is done.
